DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "https://hoziewedding.com"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
theme = "gohugo-theme-ananke"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "about us"
    url = "/about/"
    weight = -110


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
background_color_class = "bg-black"
description = ""
facebook = ""
favicon = ""
featured_image = "/images/gohugo-default-sample-hero-image.jpg"
github = ""
gitlab = ""
instagram = ""
linkedin = ""
mastodon = ""
recent_posts_number = 2
twitter = ""
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
